### PR TITLE
Update to CorePlot 1.5.1 

### PR DESCRIPTION
**Pull request by morinel**
Fix property 'positiveFormat' / 'negativeFormat' not found on object of type 'NSFormatter *' by adding casts to NSNumberFormatter
Set version to 1.5.1
Remove obsolete 1.4.1 zip file and add the 1.5.1 for easy downloading
Additionally, this version fixes the issue with Ti 3.5.0.GA that the x86_64 architecture was missing from the libCorePlot-CocoaTouch.a file --> unable to run the app in the simulator

### CODE REVIEW

**Comment by jonalter** [comment]
Hi @morinel, thank you for the PR!
Please sign our [CLA](cla.appcelerator.com) so we can merge your PR.

**Comment by morinel** [comment]
CLA signed

**Comment by jonalter** [comment]
Thank you. We will be processing this PR shortly.

**Comment by jonalter** [comment]
Merged in #5

**Pull request merged**
